services:
  postgres-db:
    image: postgres:13
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      PGUSER: 'user'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'fire-incident-db'
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - fire-incident-network

  pgadmin:
    image: dpage/pgadmin4:8.6
    container_name: pgadmin4-container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - fire-incident-network
    
  spark-master:
    container_name: spark-master
    build: .
    image: spark-custom-image
    entrypoint: ['./entrypoint.sh', 'master']
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./data:/opt/spark/data
      - ./apps:/opt/spark/apps
      - ./notebooks:/opt/spark/notebooks
      - spark-logs:/opt/spark/spark-events

    env_file:
      - .env.spark
    ports:
      - '9090:8080'
      - '7077:7077'
      - '8880:8888'
    environment:
      POSTGRES_USER: 'user'
      PGUSER: 'user'
    networks:
      - fire-incident-network
    
  
  spark-history-server:
    container_name: spark-history-server
    image: spark-custom-image
    entrypoint: ['./entrypoint.sh', 'history-server']
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    volumes:
      - spark-logs:/opt/spark/spark-events
    ports:
      - '18080:18080'
    networks:
      - fire-incident-network

      
volumes:
  postgres-db:
  pgadmin-data:
  spark-logs:

networks:
  fire-incident-network:
    name: fire-incident-network
