services:
  postgres-db:
    image: postgres:13
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fire-incident-db
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - pg-network
  pgadmin:
    image: dpage/pgadmin4:8.6
    container_name: pgadmin4-container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - pg-network
    
  spark:
    image: apache/spark:3.4.2-python3
    container_name: spark
    ports:
      - 8085:8085
      - 7077:7077
    working_dir: /opt/spark
    command: /opt/spark/sbin/start-master.sh
    environment:
      SPARK_UI_PORT: 8085
      SPARK_MODE: master
      SPARK_RPC_AUTHENTICATION_ENABLED: no
      SPARK_RPC_ENCRYPTION_ENABLED: no
      SPARK_NO_DAEMONIZE: "true"
    volumes:
      - ./:/home
      - spark-data:/opt/spark/data
    networks:
      - pg-network

volumes:
  postgres-db:
  pgadmin-data:
  spark-data:
networks:
  pg-network:
    name: pg-network
    driver: bridge